name       : libolm
version    : 3.2.13
release    : 1
source     :
    - https://gitlab.matrix.org/matrix-org/olm/-/archive/3.2.13/olm-3.2.13.tar.gz : 3226d94118ec048bc3ab40ceec1835e58837fe56752328160b347e70d3d5e444
license    : Apache-2.0
homepage   : https://gitlab.matrix.org/matrix-org/olm
component  : security.library
summary    : Implementation of the Olm and Megolm cryptographic ratchets
description: |
    Implementation of the Olm and Megolm cryptographic ratchets
builddeps  :
    - pkgconfig(libsodium)
clang      : yes
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
